In [1]:
import numpy as np
import cv2
from utilities import *

In [28]:
arrayA = np.arange(24)
arrayB = arrayA.reshape((6,4)) 
arrayB
# arrayC = np.pad(arrayB.flatten(),(0,len(arrayB)*len(arrayB[0])*2),'constant',constant_values=(0,0)).reshape((len(arrayB),len(arrayB[0]),3)) 
arrayC = arrayB.flatten().reshape((len(arrayB),len(arrayB[0]))) 
arrayC.shape

(6, 4)

In [29]:
# print(len(arrayA))
# print(len(arrayB))
# print(len(arrayB[0]))
print(arrayC)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [36]:
image=cv2.imread('testdata/tomato1.png')
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV) #將BGR轉換為HSV 
#HSV中的顏色強度參數
weaker_red = np.array([0,76,157]) 
strong_red = np.array([179,199,255])
mask_red = cv2.inRange(hsv,weaker_red,strong_red) #Threshold HSV圖像獲取輸入顏色
z_array=np.zeros((len(mask_red),len(mask_red[0])))
mask=np.stack((mask_red.copy(),z_array.copy(),z_array.copy()),2)
displayIMG(mask)

In [32]:
z=np.zeros((6,4))
c=np.stack((arrayC.copy(),z.copy(),z.copy()),2)
print(c)
print(c.shape)


[[[ 0.  0.  0.]
  [ 1.  0.  0.]
  [ 2.  0.  0.]
  [ 3.  0.  0.]]

 [[ 4.  0.  0.]
  [ 5.  0.  0.]
  [ 6.  0.  0.]
  [ 7.  0.  0.]]

 [[ 8.  0.  0.]
  [ 9.  0.  0.]
  [10.  0.  0.]
  [11.  0.  0.]]

 [[12.  0.  0.]
  [13.  0.  0.]
  [14.  0.  0.]
  [15.  0.  0.]]

 [[16.  0.  0.]
  [17.  0.  0.]
  [18.  0.  0.]
  [19.  0.  0.]]

 [[20.  0.  0.]
  [21.  0.  0.]
  [22.  0.  0.]
  [23.  0.  0.]]]
(6, 4, 3)
